// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frxjisnsikwvdmsgsmcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyeGppc25zaWt3dmRtc2dzbWNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMDcwMzMsImV4cCI6MjA3MDU4MzAzM30.SX5SCxaU2kVfCR1yWR4MbBmAxDVuSlJow-pM9Qj6970";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});